Store.Web/Controllers/PlaylistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AnyMusic.Domain.Domain;
using AnyMusic.Repository;
using AnyMusic.Service;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using AnyMusic.Domain.Domain.ViewModels;
using AnyMusic.Service.Interface;

namespace AnyMusic.Web.Controllers
{

    [Authorize]
    public class PlaylistsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IPlaylistService _playlistService;
        private readonly ITrackService _trackService;
        private readonly ITrackInPlaylistService _trackInPlaylistService;

        public PlaylistsController(ApplicationDbContext context, IPlaylistService playlistService, ITrackService trackService, ITrackInPlaylistService trackInPlaylistService)
        {
            _context = context;
            _playlistService = playlistService;
            _trackService = trackService;
            _trackInPlaylistService = trackInPlaylistService;
        }


        [Authorize]
        public async Task<IActionResult> AddToPlaylist(Guid trackId)
        {
            var track = _trackService.GetDetailsForTrack(trackId);
            if (track == null)
            {
                return NotFound();
            }
            // Get all playlists for the current user
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); 

            var playlists = _playlistService.GetAllUserPlaylists(userId)
                                                     
                                                  .Where(pl => !pl.TracksInPlaylists.Any(tp => tp.TrackId == trackId)) // Exclude playlists that already contain the track
                                                  .ToList();


            var model = new AddToPlaylistViewModel
            {
                TrackId = trackId,
                TrackName = track.TrackName,
                Playlists = playlists.Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Name
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToPlaylist(AddToPlaylistViewModel model)
        {
            if (ModelState.IsValid)
            {
                var track = _trackService.GetDetailsForTrack(model.TrackId);
                var playlist = _playlistService.GetDetailsForUserPlaylist(model.PlaylistId);

                if (track != null && playlist != null)
                {
                    _trackService.AddTrackToUserPlaylist(playlist, track);
                    return RedirectToAction("Index", "Tracks");
                }

                ModelState.AddModelError("", "Invalid track or playlist.");
            }

            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            model.Playlists = _playlistService.GetAllUserPlaylists(userId)
                .Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Name
                }).ToList();

            return View(model);
        }


        public async Task<IActionResult> RemoveTrackFromPlaylist(Guid playlistId, Guid trackId)
        {
            var trackInPlaylist = await _context.TrackInPlaylists
         .FirstOrDefaultAsync(tip => tip.PlaylistId == playlistId && tip.TrackId == trackId);

            if (trackInPlaylist == null)
            {
                return NotFound();
            }

            _context.TrackInPlaylists.Remove(trackInPlaylist);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = playlistId });
        }



        // GET: Playlists
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Filter playlists based on the current user's ID
            var userPlaylists = await _context.Playlists
                .Where(p => p.UserId == userId)
                .Include(p => p.TracksInPlaylists)
                .ToListAsync();

            return View(userPlaylists);
        }

        // GET: Playlists/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlists
          .Include(p => p.TracksInPlaylists)
          .ThenInclude(tp => tp.Track) // Include the Track details
          .FirstOrDefaultAsync(p => p.Id == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // GET: Playlists/Create
        public async Task<IActionResult> Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _context.Users.FindAsync(userId);

            if (user == null)
            {
                return Unauthorized();
            }

            var userPlaylistsCount = _playlistService.GetAllUserPlaylists(userId).Count();

            if (user.IsSubscribed != true && userPlaylistsCount >= 1)
            {
                return RedirectToAction("PremiumOnly");
            }

            return View();
        }


        // POST: Playlists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Playlist playlist)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _context.Users.FindAsync(userId);

            if (user == null)
            {
                return Unauthorized();
            }

            var userPlaylistsCount = _playlistService.GetAllUserPlaylists(userId).Count();

            if (user.IsSubscribed != true && userPlaylistsCount >= 1)
            {
                return RedirectToAction("PremiumOnly");
            }

            if (ModelState.IsValid)
            {
                playlist.Id = Guid.NewGuid();
                playlist.UserId = userId;
                _context.Add(playlist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(playlist);
        }

        public IActionResult PremiumOnly()
        {
            return View();
        }


        // GET: Playlists/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlists.FindAsync(id);
            if (playlist == null)
            {
                return NotFound();
            }
            return View(playlist);
        }

        // POST: Playlists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,Id")] Playlist playlist)
        {
            if (id != playlist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(playlist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaylistExists(playlist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(playlist);
        }

        // GET: Playlists/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // POST: Playlists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var playlist = await _context.Playlists.FindAsync(id);
            if (playlist != null)
            {
                _context.Playlists.Remove(playlist);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlaylistExists(Guid id)
        {
            return _context.Playlists.Any(e => e.Id == id);
        }
    }
}

Store.Web/Views/Tracks/Create.cshtml
@model AnyMusic.Domain.Domain.ViewModels.TrackViewModel

<h1>Create</h1>

<h4>Track</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Track.TrackName" class="control-label"></label>
                <input asp-for="Track.TrackName" class="form-control" />
                <span asp-validation-for="Track.TrackName" class="text-danger"></span>
            </div>
         @*    <div class="form-group">
                <label asp-for="Track.AlbumId" class="control-label"></label>
                <select asp-for="Track.AlbumId" class="form-control" asp-items="ViewBag.AlbumId"></select>
            </div> *@
            <div class="form-group">
                <label asp-for="Track.Duration" class="control-label"></label>
                <input asp-for="Track.Duration" class="form-control" />
                <span asp-validation-for="Track.Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Track.Rating" class="control-label"></label>
                <input asp-for="Track.Rating" class="form-control" />
                <span asp-validation-for="Track.Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="SelectedArtistIds" class="control-label">Artists</label>
                <select asp-for="SelectedArtistIds" class="form-control" asp-items="Model.Artists" multiple="multiple"></select>
                <span asp-validation-for="SelectedArtistIds" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Store.Web/Views/Tracks/Delete.cshtml
@model AnyMusic.Domain.Domain.Track

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Track</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrackName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Store.Web/Views/Tracks/Details.cshtml
@model AnyMusic.Domain.Domain.Track

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Track</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TrackName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TrackName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">Artists</dt>
        <dd class="col-sm-10">
            @string.Join(", ", Model.Artists.Select(a => a.Artist.ArtistName))
    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Store.Web/Views/Tracks/Edit.cshtml
@model AnyMusic.Domain.Domain.Track

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Track</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TrackName" class="control-label"></label>
                <input asp-for="TrackName" class="form-control" />
                <span asp-validation-for="TrackName" class="text-danger"></span>
            </div>
    
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Store.Web/Views/Tracks/Index.cshtml
@model IEnumerable<AnyMusic.Domain.Domain.Track>


@{
    ViewData["Title"] = "Tracks";
}

<div class="container mt-5">
    <div class="row mb-4 ">
        <div class="col">
            <h1 class="display-4">Browse all Tracks!</h1>
        </div>
        <div class="col text-end">
            <a class="btn btn-dark btn-lg" asp-action="Create">Create New Track</a>
            <a class="btn btn-success btn-lg" asp-action="ExportAllTracks">Export All Tracks!!!</a>
        </div>

    </div>

    @if (Model.Any())
    {
        <div class="table-responsive">
            <table class="table table-striped table-hover align-middle">
                <thead class="table-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.First().TrackName)</th>
                        <th>@Html.DisplayNameFor(model => model.First().Duration)</th>
                        <th>@Html.DisplayNameFor(model => model.First().Rating)</th>
                        <th>Artists</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.TrackName)</td>
                            <td>@Html.DisplayFor(modelItem => item.Duration) min</td>
                            <td>@Html.DisplayFor(modelItem => item.Rating) / 5</td>
                            <td>
                                @string.Join(", ", item.Artists.Select(a => a.Artist.ArtistName)) 
                            </td>
                            <td class="text-end">
                                <a class="btn btn-sm btn-outline-secondary me-2" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                <a class="btn btn-sm btn-outline-info me-2" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                <a class="btn btn-sm btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                <a asp-controller="Playlists" asp-action="AddToPlaylist" asp-route-trackId="@item.Id" class="btn btn-outline-success">Add to Playlist</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    }
    @if (!Model.Any())
    {
        <div class="row text-white fw-bold">
            <div class="col-12">
                <p class="text-center">No tracks found.</p>
            </div>
        </div>
    }
</div>